### ISSUE TITLE
Everdev installer doesn't work

### ISSUE THREAD

**Issue by zeleniy** [tonlabs/everdev#85]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
```
$ node -v
v14.19.0
```
```
$ sudo npm i -g everdev
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/everdev -> /usr/local/lib/node_modules/everdev/cli.js

> cpu-features@0.0.2 install /usr/local/lib/node_modules/everdev/node_modules/cpu-features
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.19.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/everdev/node_modules/cpu-features/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/everdev/node_modules/cpu-features/.node-gyp'
gyp ERR! System Linux 5.13.0-28-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/everdev/node_modules/cpu-features
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> ssh2@1.6.0 install /usr/local/lib/node_modules/everdev/node_modules/ssh2
> node install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.19.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/everdev/node_modules/ssh2/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/everdev/node_modules/ssh2/.node-gyp'
gyp ERR! System Linux 5.13.0-28-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--target=v14.19.0" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/everdev/node_modules/ssh2/lib/protocol/crypto
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Failed to build optional crypto binding

> @tonclient/lib-node@1.30.0 postinstall /usr/local/lib/node_modules/everdev/node_modules/@tonclient/lib-node
> node install.js

Error: EACCES: permission denied, mkdir '/root/.tonlabs/binaries/1_30'
    at Object.mkdirSync (fs.js:1013:3)
    at resolveBinariesTargetPath (/usr/local/lib/node_modules/everdev/node_modules/@tonclient/lib-node/install.js:97:16)
    at main (/usr/local/lib/node_modules/everdev/node_modules/@tonclient/lib-node/install.js:111:32)
    at /usr/local/lib/node_modules/everdev/node_modules/@tonclient/lib-node/install.js:117:15
    at Object.<anonymous> (/usr/local/lib/node_modules/everdev/node_modules/@tonclient/lib-node/install.js:122:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.tonlabs/binaries/1_30'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 (node_modules/everdev/node_modules/cpu-features):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tonclient/lib-node@1.30.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tonclient/lib-node@1.30.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-07T09_00_26_395Z-debug.log
```

**Comment by d3p** [comment]
If you really want to install in `root` using `nobody` uid, you need to grant access for it. Or try install `everdev` without `sudo`.

**Comment by zeleniy** [comment]
As i know it is impossible to install any package globally without `sudo` at least on Ubuntu.
```
$ npm i -g everdev
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zelenin/.npm/_logs/2022-02-07T12_04_21_950Z-debug.log
```

**Comment by d3p** [comment]
Check your local user permissions. Missing write access to `/usr/local/lib/node_modules`.

**Comment by Artem-Zhdanov** [comment]
@zeleniy I recommend installing node.js using [nvm](https://github.com/nvm-sh/nvm). It solves all problems related to installing modules globally.  
Let me know if this helps so I can close the issue.

**Comment by Artem-Zhdanov** [comment]
Closed due to inactivity

**Comment by zeleniy** [comment]
I have installed node.js with nvm. It doesn't help. Here is reproduction steps:

1. Create Dockerfile:
```
FROM ubuntu:18.04

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get install -y curl wget

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
# RUN npm install -g n
# RUN n 14
# RUN npm install -g everdev

WORKDIR /root/free-ton-app
```
2. Build image:
```
docker build -t free-ton-v1.0 .
```
3. Run container:
```
docker run -v `pwd`:/root/free-ton-app -it free-ton-v1.0 bash
```
4. Within container run:
```
nvm install 14
```
5. And finally run package manager:
```
npm i -g everdev
```
Or try it without Docker if you have Ubuntu installed as is.

**Comment by zeleniy** [comment]
@Artem-Zhdanov reopen issue please.

**Comment by zeleniy** [comment]
@elasticLove1 may be you can help with this issue?
